---
- name: docker push to docker hub registry
  hosts: all
  become: true
  vars_files:
  - secret.yaml
  tasks:
  - name: copy dockerfile to managed node
    copy:
      src: /home/ansible/Dockerfile
      dest: /home/ansible/

  - name: build the docker image
    command: "docker build /home/ansible/ -t cubensquare/testimage-1"

  - name: docker login
    docker_login:
      username: "{{ username }}"
      password: "{{ password }}"

  - name: docker push
    docker_image:
      name: cubensquare/testimage-1
      push : yes
  - name: test
    debug:
      var: result
  - name: test123
    command: date
    register: date_val
  - name: docker module
    docker_login:
       username: cnsss
       password: 
  - name: create container
    docker_container:
       name: cubensquare
       image: cubensquare/testimage-1
  - name: docker_login



